### PR TITLE
Add previews and descriptions to README.md

### PR DESCRIPTION
**Pull request by 1point7point4**
Let me know if I need to improve anything for this to get merged.

### CODE REVIEW

**Comment by 1point7point4** [comment]
the formatting is a bit ugly, one sec while i make it nicer

**Comment by 1point7point4** [comment]
Preview at https://github.com/1point7point4/Great-Community-Maps

**Comment by Caballero-Arepa** [comment]
Wow. Thank you very much!!

**Comment by Caballero-Arepa** [comment]
Ohh, there is no image of the Indonesia map...

**Comment by 1point7point4** [comment]
Yeah, couldn't find one (only looked in the maps channel). Maybe I'll load it up eventually, seems like it might be a fun map to play :)

For now I'll open an issue.

**Pull request merged**
